### ISSUE TITLE
Use a copy right license

### ISSUE THREAD

**Issue by carlmartensen** [sta-szek/pojo-tester#204]
Is there a legitimate need for GPL?

**Comment by sta-szek** [comment]
As proposed by https://choosealicense.com/ I wanted people to share improvements. 
@carlmartensen would you like me to change the license? What kind of license and why?

**Comment by 36893488147419103231** [comment]
I'd propose LGPL

https://stackoverflow.com/a/1114054/755804

--quotation--

LGPL allows you to use and distribute the open source software with your application without releasing the source code for your application.

GPL requires you to release the source code of your application if you choose to use and distribute the GPL licensed open source software with your application. In other words, your application must also be licensed under the GPL.

--end quotation--

From my point of view, a tester library is a corner case because even GPL allows you to run the software and the only way to run a testing library is to link with it... So I would read the license as permitting anyone to test any software, GPLed or not. But LGPL would make the right to test non-GPL code evident.

**Comment by sta-szek** [comment]
@carlmartensen feel free to make PR with new license
